package main

import (













































































}	}		log.Fatalf("Failed to start server: %v", err)	if err := router.Run(":" + cfg.Port); err != nil {	log.Printf("Report Service starting on port %s", cfg.Port)	reportHandler.RegisterRoutes(api, jwtManager)	api := router.Group("/api/v1")	// API Routes	})		})			"service": "report-service",			"status":  "healthy",		c.JSON(200, gin.H{	router.GET("/health", func(c *gin.Context) {	// Health check	router.Use(middleware.CORSMiddleware())	// CORS Middleware	router := gin.Default()	// Gin Router	jwtManager := utils.NewJWTManager(cfg.JWTSecret, 24*time.Hour, refreshExpiry)	refreshExpiry, _ := time.ParseDuration(cfg.RefreshExpiry)	// JWT Setup	reportHandler := handler.NewReportHandler(povsGRNService, exportService)	// Initialize handlers	exportService := service.NewExportService()	povsGRNService := service.NewPOvsGRNService(procurementReportRepo, procurementDB)	// Initialize services	_ = repository.NewGeneratedReportRepository(reportDB)	procurementReportRepo := repository.NewProcurementReportRepository(procurementDB)	// Initialize repositories	reportDB := mongoClient.Database("erp_reports")	// Report service's own database for storing generated report metadata	procurementDB := mongoClient.Database("erp_procurement")	// We read from the procurement database directly (read-only access)	log.Println("Connected to MongoDB successfully")	}		log.Fatalf("Failed to ping MongoDB: %v", err)	if err := mongoClient.Ping(ctx, nil); err != nil {	// Ping MongoDB to verify connection	defer mongoClient.Disconnect(context.Background())	}		log.Fatalf("Failed to connect to MongoDB: %v", err)	if err != nil {	mongoClient, err := mongo.Connect(ctx, options.Client().ApplyURI(cfg.MongoURI))	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)	// Initialize MongoDB	cfg := config.LoadConfig()func main() {)	"github.com/yourusername/erp-system/shared/utils"	"github.com/yourusername/erp-system/shared/middleware"	"github.com/yourusername/erp-system/services/report-service/internal/service"	"github.com/yourusername/erp-system/services/report-service/internal/repository"	"github.com/yourusername/erp-system/services/report-service/internal/handler"	"github.com/yourusername/erp-system/services/report-service/config"	"go.mongodb.org/mongo-driver/mongo/options"	"go.mongodb.org/mongo-driver/mongo"	"github.com/gin-gonic/gin"	"time"	"log"	"context"import (