package handler
package handler

import (
	"fmt"
	"net/http"
































































































































































}	return pages	}		pages++	if int(total)%limit > 0 {	pages := int(total) / limitfunc calculateTotalPages(total int64, limit int) int {}	c.Data(http.StatusOK, "application/pdf", buf.Bytes())	c.Header("Content-Length", fmt.Sprintf("%d", buf.Len()))	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))	c.Header("Content-Type", "application/pdf")	filename := fmt.Sprintf("PO_vs_GRN_Report_%s.pdf", time.Now().Format("20060102_150405"))	}		return		utils.ErrorResponse(c, http.StatusInternalServerError, "EXPORT_ERROR", fmt.Sprintf("Failed to generate PDF: %v", err), nil)	if err != nil {	buf, err := h.exportService.GeneratePDF(items, metrics, filters)	}		return		utils.ErrorResponse(c, http.StatusInternalServerError, "EXPORT_ERROR", err.Error(), nil)	if err != nil {	items, metrics, err := h.povsGRNService.GetAllPOvsGRNForExport(c.Request.Context(), orgID, filters)	filters := parseReportFilters(c)	}		return		utils.ErrorResponse(c, http.StatusBadRequest, "INVALID_ORG_ID", "Invalid organization ID", nil)	if err != nil {	orgID, err := primitive.ObjectIDFromHex(orgIDStr)	orgIDStr := c.Param("org_id")func (h *ReportHandler) ExportPOvsGRNPDF(c *gin.Context) {// ExportPOvsGRNPDF exports the PO vs GRN comparison as a PDF file}	c.Data(http.StatusOK, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buf.Bytes())	c.Header("Content-Length", fmt.Sprintf("%d", buf.Len()))	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))	c.Header("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")	filename := fmt.Sprintf("PO_vs_GRN_Report_%s.xlsx", time.Now().Format("20060102_150405"))	}		return		utils.ErrorResponse(c, http.StatusInternalServerError, "EXPORT_ERROR", fmt.Sprintf("Failed to generate Excel: %v", err), nil)	if err != nil {	buf, err := h.exportService.GenerateExcel(items, metrics, filters)	}		return		utils.ErrorResponse(c, http.StatusInternalServerError, "EXPORT_ERROR", err.Error(), nil)	if err != nil {	items, metrics, err := h.povsGRNService.GetAllPOvsGRNForExport(c.Request.Context(), orgID, filters)	filters := parseReportFilters(c)	}		return		utils.ErrorResponse(c, http.StatusBadRequest, "INVALID_ORG_ID", "Invalid organization ID", nil)	if err != nil {	orgID, err := primitive.ObjectIDFromHex(orgIDStr)	orgIDStr := c.Param("org_id")func (h *ReportHandler) ExportPOvsGRNExcel(c *gin.Context) {// ExportPOvsGRNExcel exports the PO vs GRN comparison as an Excel file}	})		Timestamp: time.Now(),		Message:   "PO vs GRN comparison report retrieved successfully",		},			},				TotalPages: calculateTotalPages(report.TotalItems, limit),				Total:      report.TotalItems,				Limit:      limit,				Page:       page,			Pagination: utils.PaginationMetadata{			Data: report,		Data: utils.PaginationResponse{		Success: true,	c.JSON(http.StatusOK, utils.Response{	// Return the full report with pagination info	}		return		utils.ErrorResponse(c, http.StatusInternalServerError, "REPORT_ERROR", err.Error(), nil)	if err != nil {	report, err := h.povsGRNService.GetPOvsGRNComparison(c.Request.Context(), orgID, filters, page, limit)	filters := parseReportFilters(c)	limit := utils.GetLimitParam(c)	page := utils.GetPageParam(c)	}		return		utils.ErrorResponse(c, http.StatusBadRequest, "INVALID_ORG_ID", "Invalid organization ID", nil)	if err != nil {	orgID, err := primitive.ObjectIDFromHex(orgIDStr)	orgIDStr := c.Param("org_id")func (h *ReportHandler) GetPOvsGRNComparison(c *gin.Context) {// GetPOvsGRNComparison returns the PO vs GRN comparison report data}	return filters	filters.LocationID = c.Query("location_id")	filters.Status = c.Query("status")	filters.SupplierID = c.Query("supplier_id")	}		}			filters.EndDate = &t		if t, err := time.Parse("2006-01-02", endStr); err == nil {	if endStr := c.Query("end_date"); endStr != "" {	}		}			filters.StartDate = &t		if t, err := time.Parse("2006-01-02", startStr); err == nil {	if startStr := c.Query("start_date"); startStr != "" {	filters := models.ReportFilters{}func parseReportFilters(c *gin.Context) models.ReportFilters {// parseReportFilters extracts filter parameters from the request}	protected.GET("/organizations/:org_id/reports/po-vs-grn/export/pdf", h.ExportPOvsGRNPDF)	protected.GET("/organizations/:org_id/reports/po-vs-grn/export/excel", h.ExportPOvsGRNExcel)	protected.GET("/organizations/:org_id/reports/po-vs-grn", h.GetPOvsGRNComparison)	// PO vs GRN Comparison	protected.Use(middleware.AuthMiddleware(jwtManager))	protected := router.Group("")func (h *ReportHandler) RegisterRoutes(router *gin.RouterGroup, jwtManager *utils.JWTManager) {// RegisterRoutes registers all report routes}	}		exportService:  exportService,		povsGRNService: povsGRNService,	return &ReportHandler{func NewReportHandler(povsGRNService *service.POvsGRNService, exportService *service.ExportService) *ReportHandler {}	exportService  *service.ExportService	povsGRNService *service.POvsGRNServicetype ReportHandler struct {)	"github.com/yourusername/erp-system/shared/utils"	"github.com/yourusername/erp-system/shared/middleware"	"github.com/yourusername/erp-system/services/report-service/internal/service"	"github.com/yourusername/erp-system/services/report-service/internal/models"	"go.mongodb.org/mongo-driver/bson/primitive"	"github.com/gin-gonic/gin"	"time"