FROM rabbitmq:3-management-alpine

# Set default credentials 
# Note: It's better to use environment variables at runtime, but setting defaults here
ENV RABBITMQ_DEFAULT_USER=admin
ENV RABBITMQ_DEFAULT_PASS=admin123

# This is just for railway deployment. this will not be used

