package repository
package repository

import (
	"context"
	"fmt"
	"time"

























































































































































































































































}	return counts, nil	}		counts[result.Status] = result.Count		}			continue		if err := cursor.Decode(&result); err != nil {		}			Count  int    `bson:"count"`			Status string `bson:"_id"`		var result struct {	for cursor.Next(ctx) {	counts := map[string]int{}	defer cursor.Close(ctx)	}		return nil, fmt.Errorf("failed to aggregate PO counts: %w", err)	if err != nil {	cursor, err := r.poCollection.Aggregate(ctx, pipeline)	}		}}},			"count": bson.M{"$sum": 1},			"_id":   "$status",		{{Key: "$group", Value: bson.M{		{{Key: "$match", Value: matchStage}},	pipeline := mongo.Pipeline{	}		}			matchStage["supplier_id"] = supplierID		if err == nil {		supplierID, err := primitive.ObjectIDFromHex(filters.SupplierID)	if filters.SupplierID != "" {	}		matchStage["order_date"] = dateFilter		}			dateFilter["$lte"] = endOfDay			endOfDay := filters.EndDate.Add(24*time.Hour - time.Second)		if filters.EndDate != nil {		}			dateFilter["$gte"] = *filters.StartDate		if filters.StartDate != nil {		dateFilter := bson.M{}	if filters.StartDate != nil || filters.EndDate != nil {	}		"deleted_at":      nil,		"organization_id": orgID,	matchStage := bson.M{) (map[string]int, error) {	filters models.ReportFilters,	orgID primitive.ObjectID,	ctx context.Context,func (r *ProcurementReportRepository) GetPOMetricCounts(// GetPOMetricCounts returns counts of POs by status for the metrics cards}	return grns, nil	}		return nil, fmt.Errorf("failed to decode GRNs: %w", err)	if err := cursor.All(ctx, &grns); err != nil {	var grns []*sharedModels.GoodsReceiptNote	defer cursor.Close(ctx)	}		return nil, fmt.Errorf("failed to find GRNs: %w", err)	if err != nil {	cursor, err := r.grnCollection.Find(ctx, filter, opts)	opts := options.Find().SetSort(bson.M{"receipt_date": -1})	}		"deleted_at":       nil,		"purchase_order_id": bson.M{"$in": poIDs},		"organization_id":  orgID,	filter := bson.M{	}		return []*sharedModels.GoodsReceiptNote{}, nil	if len(poIDs) == 0 {) ([]*sharedModels.GoodsReceiptNote, error) {	poIDs []primitive.ObjectID,	orgID primitive.ObjectID,	ctx context.Context,func (r *ProcurementReportRepository) GetGRNsByPurchaseOrderIDs(// GetGRNsByPurchaseOrderIDs retrieves all GRNs for a list of PO IDs}	return pos, nil	}		return nil, fmt.Errorf("failed to decode purchase orders: %w", err)	if err := cursor.All(ctx, &pos); err != nil {	var pos []*sharedModels.PurchaseOrder	defer cursor.Close(ctx)	}		return nil, fmt.Errorf("failed to find purchase orders: %w", err)	if err != nil {	cursor, err := r.poCollection.Find(ctx, filter, opts)	opts := options.Find().SetSort(bson.M{"order_date": -1})	}		}			}}				sharedModels.POStatusDraft,				sharedModels.POStatusConfirmed,				sharedModels.POStatusSent,			filter["status"] = bson.M{"$in": []sharedModels.POStatus{		case "pending":			filter["status"] = sharedModels.POStatusPartiallyReceived		case "partial":			filter["status"] = sharedModels.POStatusReceived		case "matched":		switch filters.Status {	if filters.Status != "" {	}		}			filter["supplier_id"] = supplierID		if err == nil {		supplierID, err := primitive.ObjectIDFromHex(filters.SupplierID)	if filters.SupplierID != "" {	}		filter["order_date"] = dateFilter		}			dateFilter["$lte"] = endOfDay			endOfDay := filters.EndDate.Add(24*time.Hour - time.Second)		if filters.EndDate != nil {		}			dateFilter["$gte"] = *filters.StartDate		if filters.StartDate != nil {		dateFilter := bson.M{}	if filters.StartDate != nil || filters.EndDate != nil {	}		"deleted_at":      nil,		"organization_id": orgID,	filter := bson.M{) ([]*sharedModels.PurchaseOrder, error) {	filters models.ReportFilters,	orgID primitive.ObjectID,	ctx context.Context,func (r *ProcurementReportRepository) GetAllPurchaseOrdersForReport(// GetAllPurchaseOrdersForReport retrieves ALL purchase orders matching filters (no pagination, for export)}	return pos, total, nil	}		return nil, 0, fmt.Errorf("failed to decode purchase orders: %w", err)	if err := cursor.All(ctx, &pos); err != nil {	var pos []*sharedModels.PurchaseOrder	defer cursor.Close(ctx)	}		return nil, 0, fmt.Errorf("failed to find purchase orders: %w", err)	if err != nil {	cursor, err := r.poCollection.Find(ctx, filter, opts)		SetLimit(int64(limit))		SetSkip(skip).		SetSort(bson.M{"order_date": -1}).	opts := options.Find().	skip := int64((page - 1) * limit)	// Find with pagination	}		return nil, 0, fmt.Errorf("failed to count purchase orders: %w", err)	if err != nil {	total, err := r.poCollection.CountDocuments(ctx, filter)	// Count total	}		}			// No additional filter for "all" or unknown		default:			}}				sharedModels.POStatusDraft,				sharedModels.POStatusConfirmed,				sharedModels.POStatusSent,			filter["status"] = bson.M{"$in": []sharedModels.POStatus{		case "pending":			filter["status"] = sharedModels.POStatusPartiallyReceived		case "partial":			filter["status"] = sharedModels.POStatusReceived		case "matched":		switch filters.Status {	if filters.Status != "" {	// Status filter — maps UI status to PO statuses	}		}			filter["supplier_id"] = supplierID		if err == nil {		supplierID, err := primitive.ObjectIDFromHex(filters.SupplierID)	if filters.SupplierID != "" {	// Supplier filter	}		filter["order_date"] = dateFilter		}			dateFilter["$lte"] = endOfDay			endOfDay := filters.EndDate.Add(24*time.Hour - time.Second)			// Set end date to end of day		if filters.EndDate != nil {		}			dateFilter["$gte"] = *filters.StartDate		if filters.StartDate != nil {		dateFilter := bson.M{}	if filters.StartDate != nil || filters.EndDate != nil {	// Date range filter	}		"deleted_at":      nil,		"organization_id": orgID,	filter := bson.M{) ([]*sharedModels.PurchaseOrder, int64, error) {	page, limit int,	filters models.ReportFilters,	orgID primitive.ObjectID,	ctx context.Context,func (r *ProcurementReportRepository) GetPurchaseOrders(// GetPurchaseOrders retrieves purchase orders with filters for reporting}	}		grnCollection: db.Collection("goods_receipt_notes"),		poCollection:  db.Collection("purchase_orders"),	return &ProcurementReportRepository{func NewProcurementReportRepository(db *mongo.Database) *ProcurementReportRepository {}	grnCollection *mongo.Collection	poCollection  *mongo.Collectiontype ProcurementReportRepository struct {)	"go.mongodb.org/mongo-driver/mongo/options"	"go.mongodb.org/mongo-driver/mongo"	"go.mongodb.org/mongo-driver/bson/primitive"	"go.mongodb.org/mongo-driver/bson"	sharedModels "github.com/yourusername/erp-system/shared/models"	"github.com/yourusername/erp-system/services/report-service/internal/models"