package models
package models

import (
	"time"










































































































}	TotalItems           int64                   `json:"total_items"`	ActionItems          []ActionItem            `json:"action_items"`	Items                []POvsGRNComparisonItem `json:"items"`	VarianceDistribution []VarianceDistribution  `json:"variance_distribution"`	Metrics              POvsGRNMetrics          `json:"metrics"`type POvsGRNReportResponse struct {// POvsGRNReportResponse is the complete response for the PO vs GRN comparison page}	PONumber    string `json:"po_number"`	POID        string `json:"po_id"`	Description string `json:"description"`	Title       string `json:"title"`	Type        string `json:"type"` // critical, warning, info	ID          string `json:"id"`type ActionItem struct {// ActionItem represents an action item derived from PO vs GRN analysis}	Color string  `json:"color"`	Value float64 `json:"value"`	Name  string  `json:"name"`type VarianceDistribution struct {// VarianceDistribution holds the variance distribution for the chart}	CompletedPercent  float64 `json:"completed_percent"`	VariancePercent   float64 `json:"variance_percent"`	TotalGRNValue     float64 `json:"total_grn_value"`	TotalPOValue      float64 `json:"total_po_value"`	TotalVariance     float64 `json:"total_variance"`	ExcessPOs         int     `json:"excess_pos"`	PendingPOs        int     `json:"pending_pos"`	PartialPOs        int     `json:"partial_pos"`	CompletedPOs      int     `json:"completed_pos"`	TotalPOs          int     `json:"total_pos"`type POvsGRNMetrics struct {// POvsGRNMetrics holds the summary metrics for the PO vs GRN comparison}	Status       string  `json:"status"` // MATCHED, PARTIAL, EXCESS, PENDING	ValueVariance float64 `json:"value_variance"`	GRNValue     float64 `json:"grn_value"`	POValue      float64 `json:"po_value"`	UnitPrice    float64 `json:"unit_price"`	VariancePct  float64 `json:"variance_pct"`	Variance     float64 `json:"variance"`	RejectedQty  float64 `json:"rejected_qty"`	AcceptedQty  float64 `json:"accepted_qty"`	GRNQty       float64 `json:"grn_qty"`	POQty        float64 `json:"po_qty"`	ProductName  string  `json:"product_name"`	SKU          string  `json:"sku"`	ProductID    string  `json:"product_id"`	SupplierName string  `json:"supplier_name"`	SupplierID   string  `json:"supplier_id"`	OrderDate    string  `json:"order_date"`	PONumber     string  `json:"po_number"`	POID         string  `json:"po_id"`type POvsGRNComparisonItem struct {// POvsGRNComparisonItem represents a single line-item comparison between a PO item and its GRN receipt}	LocationID string     `bson:"location_id,omitempty" json:"location_id,omitempty"`	Status     string     `bson:"status,omitempty" json:"status,omitempty"`	SupplierID string     `bson:"supplier_id,omitempty" json:"supplier_id,omitempty"`	EndDate    *time.Time `bson:"end_date,omitempty" json:"end_date,omitempty"`	StartDate  *time.Time `bson:"start_date,omitempty" json:"start_date,omitempty"`type ReportFilters struct {// ReportFilters holds the filter criteria for a report}	ExpiresAt      time.Time          `bson:"expires_at" json:"expires_at"`	FilePath       string             `bson:"file_path" json:"file_path"`	FileSize       int64              `bson:"file_size" json:"file_size"`	GeneratedAt    time.Time          `bson:"generated_at" json:"generated_at"`	GeneratedBy    primitive.ObjectID `bson:"generated_by" json:"generated_by"`	Filters        ReportFilters      `bson:"filters" json:"filters"`	Title          string             `bson:"title" json:"title"`	Format         ReportFormat       `bson:"format" json:"format"`	Type           ReportType         `bson:"type" json:"type"`	OrganizationID primitive.ObjectID `bson:"organization_id" json:"organization_id"`	ID             primitive.ObjectID `bson:"_id,omitempty" json:"id"`type GeneratedReport struct {// GeneratedReport tracks generated reports)	ReportFormatExcel ReportFormat = "excel"	ReportFormatPDF   ReportFormat = "pdf"const (type ReportFormat string// ReportFormat defines the export format)	ReportTypeReorderStatus ReportType = "reorder_status"	ReportTypePOvsGRN      ReportType = "po_vs_grn"const (type ReportType string// ReportType defines the type of report)	"go.mongodb.org/mongo-driver/bson/primitive"